
DROP TABLE REPVENTAS CASCADE CONSTRAINTS;

CREATE TABLE REPVENTAS (
 NUMERO_REP NUMBER(3) NOT NULL,   --N�mero de representante de ventas
 NOMBRE   VARCHAR(15) NOT NULL, --Nombre del representante de ventas
 EDAD     NUMBER(2) ,           --Edad del representante de ventas
 OFICINA_REP NUMBER(2),    --Oficina donde trabaja el repres de ventas
 DIRECTOR NUMBER(3),       --Director del representante de ventas
 NUM_VENTAS NUMBER(2),      --N�mero de ventas realizadas por el representante
 IMP_VENTAS NUMBER(7,2) NOT NULL,  --Ventas acumuladas del rep de ventas
 CONSTRAINT PK_REPVENTAS PRIMARY KEY (NUMERO_REP)
);

INSERT INTO REPVENTAS VALUES (110,'Antonio Casado',41,11,101,2,707);
INSERT INTO REPVENTAS VALUES (106,'Jose Sanchez',52,11,NULL,15,1612);
INSERT INTO REPVENTAS VALUES (109,'Maria Gutierrez',31,11,106,2,1999);
INSERT INTO REPVENTAS VALUES (103,'Pablo Cruz',29,12,104,5,1286);
INSERT INTO REPVENTAS VALUES (101,'David Ruiz',45,12,104,2,2001);
INSERT INTO REPVENTAS VALUES (104,'Juan Agudo',33,12,106,12,2200);
INSERT INTO REPVENTAS VALUES (105,'Pedro Adams',37,13,104,23,2054);
INSERT INTO REPVENTAS VALUES (108,'Carlos Figo',62,21,106,3,2100);
INSERT INTO REPVENTAS VALUES (102,'Sara Agudo',48,21,108,22,2789);
INSERT INTO REPVENTAS VALUES (107,'Juani Annea',49,22,108,4,1090);

INSERT INTO REPVENTAS VALUES (200,'Anonimo',NULL,NULL,NULL,7,1590);
INSERT INTO REPVENTAS VALUES (201,'Anonima',NULL,NULL,NULL,3,3500);

COMMIT; 

REM ***************TABLA OFICINAS ***********************

DROP TABLE OFICINAS CASCADE CONSTRAINTS;

CREATE TABLE OFICINAS (
OFICINA NUMBER(2) NOT NULL,     --c�digo de la oficina 
CIUDAD  VARCHAR(15) NOT NULL,   --ciudad donde esta situada la oficina
COD_REGION  NUMBER(2) NOT NULL,  --Cod regi�n donde se adscribe la oficina
DIRECTOR    NUMBER(3),           --Representante de ventas director de oficina
TOTAL_VENTAS       NUMBER(9, 2) NOT NULL,  --Ventas acumuladas de la oficina
	CONSTRAINT PK_OFICINAS PRIMARY KEY (OFICINA));


INSERT INTO OFICINAS VALUES (11, 'Alicante',2,106,4900);
INSERT INTO OFICINAS VALUES (12, 'Barcelona',3,	104,	4900);
INSERT INTO OFICINAS VALUES (13,'Valencia',2, 	105, 2303);
INSERT INTO OFICINAS VALUES (21,'Cádiz',1,108,	4988);
INSERT INTO OFICINAS VALUES (22,'Sevilla',1,108, 1780);
INSERT INTO OFICINAS VALUES (23,'Huelva',1,NULL, 1000);
INSERT INTO OFICINAS VALUES (30,'Guadalajara',4,NULL, 1000);

COMMIT;


REM ***************TABLA REGIONES ***********************

DROP TABLE REGIONES CASCADE CONSTRAINTS;

CREATE TABLE REGIONES (
COD_REGION  NUMBER(2) NOT NULL,  -- Cod regi�n donde se adscribe la oficina
NOMBRE_RE   VARCHAR2(25), --Nombre de regi�n
	CONSTRAINT PK_REGION PRIMARY KEY (COD_REGION));

INSERT INTO REGIONES VALUES (1, 'ANDALUCIA');
INSERT INTO REGIONES VALUES (2, 'LEVANTE');
INSERT INTO REGIONES VALUES (3, 'CATALUÑA');
INSERT INTO REGIONES VALUES (4, 'CENTRO');
INSERT INTO REGIONES VALUES (5, 'EXTREMADURA');
INSERT INTO REGIONES VALUES (6, 'NORTE');

COMMIT;


----------------

-- 1
SELECT NOMBRE FROM REPVENTAS
WHERE DIRECTOR = (
    SELECT NUMERO_REP
    FROM REPVENTAS 
    WHERE NOMBRE LIKE 'Juan Agudo');

-- 2
SELECT r.NOMBRE_RE
FROM OFICINAS o
JOIN REGIONES r ON o.COD_REGION = r.COD_REGION 
WHERE o.DIRECTOR IS NULL;


-- 3

SELECT r.NOMBRE
FROM REPVENTAS r 
JOIN OFICINAS o ON o.OFICINA = r.OFICINA_REP
JOIN REGIONES reg ON reg.COD_REGION = o.COD_REGION
WHERE reg.NOMBRE_RE LIKE 'LEVANTE';


-- 4
SELECT NOMBRE_RE FROM REGIONES 
WHERE COD_REGION NOT IN (
    SELECT COD_REGION FROM OFICINAS
);


-- 6
SELECT NOMBRE, EDAD, TO_CHAR(sysdate - (EDAD * 365) , 'YYYY') AS ANNO
FROM REPVENTAS
WHERE EDAD IS NOT NULL;


-- 7
SELECT OFICINA_REP FROM (
    SELECT * FROM (
        SELECT OFICINA_REP, SUM(NUM_VENTAS) AS SUMA FROM REPVENTAS
        GROUP BY OFICINA_REP
    ) ORDER BY SUMA DESC
) WHERE ROWNUM = 1;



-- 8
SELECT COUNT(*)
FROM REPVENTAS
WHERE NUMERO_REP IN (
    SELECT DIRECTOR FROM REPVENTAS
)
GROUP BY OFICINA_REP
HAVING OFICINA_REP = 11;


-- 9
SELECT NOMBRE FROM (
    SELECT * FROM (
        SELECT NOMBRE, SUM(NUM_VENTAS) AS VENTAS
        FROM REPVENTAS
        GROUP BY NOMBRE
    ) ORDER BY VENTAS DESC
)
WHERE ROWNUM = 1;


-- 10
SELECT COUNT(*)
FROM REPVENTAS r
JOIN OFICINAS o ON o.OFICINA = r.OFICINA_REP
JOIN REGIONES reg ON reg.COD_REGION = o.COD_REGION
WHERE reg.NOMBRE_RE LIKE 'CATALUÑA' 
AND
r.NUMERO_REP IN (
    SELECT DIRECTOR FROM REPVENTAS
);


-- 11
SELECT reg.NOMBRE_RE, NVL(SUM(o.TOTAL_VENTAS), 0)
FROM REPVENTAS r
right JOIN OFICINAS o ON o.OFICINA = r.OFICINA_REP
full JOIN REGIONES reg ON reg.COD_REGION = o.COD_REGION
GROUP BY reg.NOMBRE_RE;


-- 12
SELECT reg.NOMBRE_RE, concat(TO_CHAR( NVL(SUM(o.TOTAL_VENTAS), 0), '999G999D99'), '€')
FROM REPVENTAS r
right JOIN OFICINAS o ON o.OFICINA = r.OFICINA_REP
full JOIN REGIONES reg ON reg.COD_REGION = o.COD_REGION
GROUP BY reg.NOMBRE_RE;

-- 13
SELECT OFICINA_REP
FROM (
    SELECT OFICINA_REP, SUM(NUM_VENTAS)
    FROM REPVENTAS
    GROUP BY OFICINA_REP
    ORDER BY SUM(NUM_VENTAS) DESC
) WHERE ROWNUM = 1;




-- 14
SELECT DISTINCT reg.NOMBRE_RE
FROM REPVENTAS r
JOIN OFICINAS o ON o.OFICINA = r.OFICINA_REP
JOIN REGIONES reg ON reg.COD_REGION = o.COD_REGION
WHERE o.OFICINA = (
    SELECT OFICINA_REP
    FROM (
        SELECT OFICINA_REP, SUM(NUM_VENTAS)
        FROM REPVENTAS
        GROUP BY OFICINA_REP
        ORDER BY SUM(NUM_VENTAS) DESC
    ) WHERE ROWNUM = 1
);


-- 15





SELECT * FROM OFICINAS;
SELECT * FROM REGIONES;
SELECT * FROM REPVENTAS;


