-- Ejercicio 2

-- 0
SELECT * FROM TESTS.AVION;

-- 1
SELECT ORIGEN, DESTINO FROM RUTA;

-- 2
SELECT DISTINCT ORIGEN, DESTINO FROM RUTA;

-- 3
SELECT OCUPACION, TO_CHAR(FECHA, 'DD-MON-YYYY') AS FECHA2
FROM VUELO
ORDER BY FECHA DESC;

-- 4
SELECT MODELO, PLAZAS, (PLAZAS * 1.1) AS PlazasDefinitivas
FROM AVION;

-- 5
SELECT COMPAN FROM RUTA
WHERE DESTINO LIKE 'BARCELONA';

-- 6
SELECT MAT, MODELO, PLAZAS, FECHA_REV
FROM AVION
WHERE FECHA_REV IS NULL;


-- 7 
SELECT v.COD, v.MAT, v.OCUPACION, r.DESTINO, v.FECHA, r.ORIGEN
FROM VUELO v
left outer join RUTA r
ON v.COD = r.COD;


-- 8 
SELECT r.ORIGEN, r.DESTINO, r.COMPAN, v.OCUPACION, a.PLAZAS
FROM VUELO v

INNER JOIN RUTA r
ON v.COD = r.COD

INNER JOIN AVION a
ON v.MAT = a.MAT

WHERE v.OCUPACION = a.PLAZAS;


-- 9
SELECT r1.COMPAN, r2.COMPAN, r1.DESTINO
FROM RUTA r1
JOIN RUTA r2
ON r1.DESTINO = r2.DESTINO
WHERE r1.COMPAN < r2.COMPAN;



COMMIT;



SELECT * FROM VUELO;
SELECT * FROM RUTA;
SELECT * FROM AVION;